config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations"
    }
    devise_scope :user do
      get "sign_in", to: "users/sessions#new"
      get "sign_out", to: "users/sessions#destroy"
    end

    get "/tours", to: "tours#index"
    namespace :admin do
      root "index#home"
      resources :users, only: %i(index destroy)
      resources :reviews, only: %i(index destroy)
      resources :categories
      resources :locations
      resources :travellings
      resources :bookings, only: :index do
        member do
          patch :change_status
        end
      end
      resources :tours do
        member do
          patch :change_status
        end
      end
    end
    resources :users, expect: %i(index destroy)
    resources :comments, only: :create
    resources :tours, only: %i(show index) do
      resources :reviews
    end
    resources :reviews do
      resources :likes, only: %i(new create show destroy)
    end
    resources :bookings, only: %i(new create index) do
      member do
        patch :change_status
      end
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :travellings_start_id, class_name: Travelling.name,
    foreign_key: :location_start_id, dependent: :destroy
  has_many :travellings_end_id, class_name: Travelling.name,
    foreign_key: :location_end_id, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  scope :sort_by_name, ->{order name: :desc}
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :admin_user
  before_action :load_location, except: %i(create index)

  def create
    @location = Location.new location_params
    if @location.save
      flash[:success] = t ".add_location_success"
    else
      flash[:danger] = t ".add_location_error"
    end
    redirect_to admin_locations_path
  end

  def index
    @location = Location.new
    @locations = Location.sort_by_name.paginate page: params[:page],
      per_page: Settings.app.user.per_page
  end

  def edit; end

  def update
    if @location.update_attributes location_params
      flash[:success] = t ".update_location_success"
    else
      flash[:danger] = t ".update_location_error"
    end
    redirect_to admin_locations_path
  end

  def destroy
    if @location.destroy
      flash[:success] = t ".delete_location_success"
    else
      flash[:danger] = t ".delete_location_error"
    end
    redirect_to admin_locations_path
  end

  private

  def location_params
    params.require(:location).permit :name
  end

  def load_location
    @location = Location.find_by id: params[:id]
    return if @location
    flash[:danger] = t "location.action.location_not_found"
    redirect_to :root
  end
end

app/views/admin/locations/_form.html.erb
<%= form_for [:admin, @location], html: {class: "form-inline inline-box"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.text_field :name, placeholder: t(".name"), class: "form-control"  %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary mb-2" %>
<% end %>

app/views/admin/locations/_location.html.erb
<tr>
  <td></td>
  <td><%= location.name %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_location_path(location) %>
  </td>
  <td>
    <%= link_to t(".delete"), admin_location_path(location), method: :delete,
      data: { confirm: t(".you_sure") } %>
  </td>
</tr>

app/views/admin/locations/index.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <h1><%= t(".title") %></h1>
  <% provide(:button_text, t(".button_create")) %>
  <div>
    <%= render "form" %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t ".sno" %></th>
        <th><%= t ".name" %></th>
        <th><%= t ".edit" %></th>
        <th><%= t ".delete" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @locations %>
    </tbody>
  </table>
  <%= will_paginate %>
<div>