config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations"
    }
    devise_scope :user do
      get "sign_in", to: "users/sessions#new"
      get "sign_out", to: "users/sessions#destroy"
    end

    get "/tours", to: "tours#index"
    namespace :admin do
      root "index#home"
      resources :users, only: %i(index destroy)
      resources :reviews, only: %i(index destroy)
      resources :categories
      resources :locations
      resources :travellings
      resources :bookings, only: :index do
        member do
          patch :change_status
        end
      end
      resources :tours do
        member do
          patch :change_status
        end
      end
    end
    resources :users, expect: %i(index destroy)
    resources :comments, only: :create
    resources :tours, only: %i(show index) do
      resources :reviews
    end
    resources :reviews do
      resources :likes, only: %i(new create show destroy)
    end
    resources :bookings, only: %i(new create index) do
      member do
        patch :change_status
      end
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  enum status: {open: 0, close: 1}
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :category
  belongs_to :travelling
  scope :order_by_create, ->{order created_at: :desc}
  scope :open_tour, ->{where(status: "open")}
  scope :load_tours_by_filter, (lambda do |title|
    (where "title LIKE ?", "%#{title}%")
  end)
  delegate :location_start, :location_end, to: :travelling

  mount_uploader :image, PictureUploader
  validates :title, presence: true,
    length: {maximum: Settings.app.tour.title_max_length}
  validates :description, presence: true
  validates :price, presence: true
  validates :num_people, presence: true
  validate :image_size

  def self.search_by search_term
    where "title LIKE ? OR price LIKE ?", "%#{search_term}%", "%#{search_term}%"
  end

  def average_review
    return reviews.average(:rating) if reviews.present?
  end

  private

  # Validates the size of an uploaded picture.
  def image_size
    return unless image.size > Settings.app.user.image_size_mb.megabytes
    errors.add(:image, I18n.t("users.action.maximum_size_err"))
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :admin_user
  before_action :load_tour, except: %i(create new index)
  before_action :load_categories, except: %i(index destroy status)
  before_action :load_travellings, except: %i(index destroy status)

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new tour_params
    if @tour.save
      flash[:success] = t ".add_tour_success"
      redirect_to admin_tours_path
    else
      render :new
    end
  end

  def index
    @search = Tour.ransack params[:q]
    @tours = @search.result.order_by_create.paginate page:
      params[:page], per_page: Settings.app.user.per_page
  end

  def edit; end

  def update
    if @tour.update_attributes tour_params
      flash[:success] = t ".tour_updated"
      redirect_to admin_tours_path
    else
      render :edit
    end
  end

  def destroy
    if @tour.destroy
      flash[:success] = t ".tour_deleted"
    else
      flash[:danger] = t ".tour_delete_error"
    end
    redirect_to admin_tours_path
  end

  def change_status
    @tour.close? ? @tour.open! : @tour.close!
    respond_to do |format|
      format.js
    end
  end

  private

  def tour_params
    params.require(:tour).permit :title, :description, :image, :price,
      :num_people, :tour_start, :tour_finish, :category_id, :travelling_id
  end

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "tours.action.tour_not_found"
    redirect_to :root
  end

  def load_categories
    @categories = Category.sort_by_name_at_asc.map{|c| [c.name, c.id]}
  end

  def load_travellings
    @travellings = Travelling.sort_by_name_location_asc.map do |t|
      ["#{t.location_start.name} - #{t.location_end.name}", t.id]
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  authorize_resource
  before_action :load_tour, :load_review, only: :show

  def index
    @search = Tour.ransack params[:q]
    @tours = @search.result.open_tour.includes(:category).order_by_create.paginate page:
      params[:page], per_page: Settings.app.page
  end

  def show; end

  private

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t ".danger"
    redirect_to root_path
  end

  def load_review
    @reviews = @tour.reviews.order_by_create.paginate page: params[:page],
      per_page: Settings.app.page
    return if @review
  end
end

app/views/admin/tours/_change_status.html.erb
<%= is_status_close? tour %>

app/views/admin/tours/_form.html.erb
<%= form_for [:admin, @tour] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :title, t(".title") %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :category, t(".category") %>
  <div class="form-group">
    <%= f.select :category_id, @categories, {selected: @categories.first},
      {class: "form-control"} %>
  </div>

  <%= f.label :travelling, t(".travelling") %>
  <div class="form-group">
    <%= f.select :travelling_id, @travellings, {selected: @travellings.first},
      {class: "form-control"} %>
  </div>

  <%= f.label :description, t(".description") %>
  <%= f.text_area :description, size: Settings.app.tour.text_area_size,
    class: "form-control" %>

  <%= f.label :image, t(".image") %>
  <span class="picture">
    <%= f.file_field :image, accept: Settings.app.user.image_accept %>
  </span>
  <div><%= image_tag @tour.image.url(:thumb) if @tour.image? %></div>

  <%= f.label :price, t(".price") %>
  <%= f.number_field :price, value: Settings.app.tour.value_price,
      min: Settings.app.tour.min_price, class: "form-control" %>

  <%= f.label :num_people, t(".num_people") %>
  <%= f.number_field :num_people, value: Settings.app.tour.value_people,
      min: Settings.app.tour.min_people, class: "form-control" %>

  <%= f.label :tour_start, t(".tour_start") %>
  <div class="form-datetime">
    <%= f.datetime_select :tour_start %>
  </div>

  <%= f.label :tour_finish, t(".tour_finish") %>
  <div class="form-datetime">
    <%= f.datetime_select :tour_finish %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/tours/_tour.html.erb
<tr>
  <td></td>
  <td><%= tour.title %></td>
  <td><%= l tour.tour_start, format: :long %></td>
  <td><%= l tour.tour_finish, format: :long %></td>
  <td><%= tour.location_start.name %> - <%= tour.location_end.name %></td>
  <td><%= number_to_currency tour.price %></td>
  <td id="tour_status-<%= tour.id %>">
    <%= is_status_close? tour %>
  </td>
  <td>
    <%= link_to t(".edit"), edit_admin_tour_path(tour) %> - 
    <%= link_to t(".delete"), admin_tour_path(tour), method: :delete,
      data: { confirm: t(".you_sure") } %>
  </td>
</tr>

app/views/admin/tours/change_status.js.erb
$('#tour_status-<%= @tour.id %>').html('<%=  j render "admin/tours/change_status",
  tour: @tour %>');

app/views/admin/tours/edit.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <% provide(:button_text, t(".save_change")) %>
  <h1 class="text-center"><%= t(".title") %></h1>
  <div class="row justify-content-center">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/tours/index.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <h1 class="text-center"><%= t(".title") %></h1>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= search_form_for @search do |f| %>
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-12 p-1">
            <%= f.text_field :title_cont, class: "form-control",
              placeholder: t(".tourname") %>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 p-1">
            <%= f.number_field :price_gteq, class: "form-control",
              placeholder: t(".pricestart") %>
          </div>
          <div class="col-lg-1 col-md-1 col-sm-12 p-1">
            <%= f.number_field :price_lteq, class: "form-control",
              placeholder: t(".priceand") %>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 p-1">
          <%= f.number_field :num_people_eq, class: "form-control",
            placeholder: t(".people") %>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 p-1">
            <%= f.collection_select :category_id_eq, Category.all, :id, :name,
            {include_blank: t(".category")}, {class: "form-control"} %>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 p-1" >
            <%= f.submit t(".search"), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <%= link_to t(".new_tour"), new_admin_tour_path, class: "btn-custom btn btn-primary" %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t ".sno" %></th>
        <th><%= sort_link(@search, :title, t(".title")) %></th>
        <th><%= sort_link(@search, :tour_start, t(".start")) %></th>
        <th><%= sort_link(@search, :tour_finish, t(".finish")) %></th>
        <th><%= t ".travelling" %></th>
        <th><%= sort_link(@search, :price, t(".price")) %></th>
        <th><%= t ".status" %></th>
        <th><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @tours %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/admin/tours/new.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <% provide(:button_text, t(".button_create")) %>
  <h1 class="text-center"><%= t(".title") %></h1>
  <div class="row justify-content-center">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>