config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations"
    }
    devise_scope :user do
      get "sign_in", to: "users/sessions#new"
      get "sign_out", to: "users/sessions#destroy"
    end

    get "/tours", to: "tours#index"
    namespace :admin do
      root "index#home"
      resources :users, only: %i(index destroy)
      resources :reviews, only: %i(index destroy)
      resources :categories
      resources :locations
      resources :travellings
      resources :bookings, only: :index do
        member do
          patch :change_status
        end
      end
      resources :tours do
        member do
          patch :change_status
        end
      end
    end
    resources :users, expect: %i(index destroy)
    resources :comments, only: :create
    resources :tours, only: %i(show index) do
      resources :reviews
    end
    resources :reviews do
      resources :likes, only: %i(new create show destroy)
    end
    resources :bookings, only: %i(new create index) do
      member do
        patch :change_status
      end
    end
  end
end

app/models/travelling.rb
class Travelling < ApplicationRecord
  has_many :tours, dependent: :destroy
  belongs_to :location_start, class_name: Location.name,
    foreign_key: :location_start_id
  belongs_to :location_end, class_name: Location.name,
    foreign_key: :location_end_id
  scope :sort_by_created_desc, ->{order created_at: :desc}
  scope :sort_by_name_location_asc, (lambda do
    Travelling.joins(:location_start).merge(Location.order(name: :asc))
  end)
  validates :location_start, uniqueness: {scope: :location_end}
end

app/controllers/admin/travellings_controller.rb
class Admin::TravellingsController < ApplicationController
  before_action :admin_user
  before_action :load_locations, except: :destroy
  before_action :load_travelling, except: %i(create index)
  before_action :build_travelling, only: :index

  def create
    @travelling = Travelling.new travelling_params
    if @travelling.save
      flash[:success] = t ".add_travelling_success"
    else
      flash[:danger] = t ".add_travelling_error"
    end
    redirect_to admin_travellings_path
  end

  def index
    @travellings = Travelling.sort_by_created_desc.paginate page: params[:page],
      per_page: Settings.app.user.per_page
  end

  def edit; end

  def update
    if @travelling.update_attributes travelling_params
      flash[:success] = t ".update_travelling_success"
      redirect_to admin_travellings_path
    else
      flash[:danger] = t ".update_travelling_error"
      render :edit
    end
  end

  def destroy
    if @travelling.destroy
      flash[:success] = t ".delete_travelling_success"
    else
      flash[:danger] = t ".delete_travelling_error"
    end
    redirect_to admin_travellings_path
  end

  private

  def travelling_params
    params.require(:travelling).permit :location_start_id,
      :location_end_id
  end

  def load_locations
    @locations = Location.all.map{|l| [l.name, l.id]}
  end

  def load_travelling
    @travelling = Travelling.find_by id: params[:id]
    return if @travelling
    flash[:danger] = t "travelling.action.travelling_not_found"
    redirect_to :root
  end

  def build_travelling
    @travelling = Travelling.new
  end
end

app/views/admin/travellings/_form.html.erb
<%= form_for [:admin, @travelling], html: {class: "form-inline inline-box"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.select :location_start_id, @locations, {selected: @locations.first},
      { class: "form-control"} %>
  </div>
  <h4><%= t(".goto") %></h4>
  <div class="form-group">
    <%= f.select :location_end_id, @locations, {selected: @locations.second},
      {class: "form-control"} %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary mb-2" %>
<% end %>

app/views/admin/travellings/_travelling.html.erb
<tr>
  <td></td>
  <td><%= travelling.location_start.name %></td>
  <td><%= travelling.location_end.name %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_travelling_path(travelling) %>
  </td>
  <td>
    <%= link_to t(".delete"), admin_travelling_path(travelling), method: :delete,
      data: { confirm: t(".you_sure") } %>
  </td>
</tr>

app/views/admin/travellings/edit.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <% provide(:button_text, t(".save_change")) %>
  <h1><%= t(".title") %></h1>
    <%= render "form" %>
  </div>
</div>

app/views/admin/travellings/index.html.erb
<div class="admin_layout">
  <% provide(:title, t(".title")) %>
  <h1><%= t(".title") %></h1>
  <% provide(:button_text, t(".button_create")) %>
  <div>
    <%= render "form" %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t ".sno" %></th>
        <th><%= t ".start" %></th>
        <th><%= t ".end" %></th>
        <th><%= t ".edit" %></th>
        <th><%= t ".delete" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @travellings %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>